### PR TITLE
Allow command schemes in URIs

### LINKED ISSUE #468: Support VS Code commands in description
We'd like to be able to add VS Code commands (i.e. `[arbitary text](command:command-goes-here)`) in the description view to help people resolve SA issues. However, react-markdown by default does not allow vscode: schemes and the command gets removed from the final rendering.

The good news is react-markdown can also be customized to allow different schemes: https://github.com/remarkjs/react-markdown#uritransformer.

### PR DESCRIPTION
**Pull request by 50Wliu**
Fixes #468.

### CODE REVIEW

**Review by jeffersonking — APPROVED** [review]

**Comment by jeffersonking** [comment]
@50Wliu Thanks! I'm going to merge this in a bit later. I'm working on a new feature and need a sample PR to test with.

**Review by chrishuynhc — APPROVED** [review]

**Comment by chrishuynhc** [comment]
@jeffersonking do you think we will be able to merge this PR today? We are hoping to release a feature on our side that relies on this change and wanted to avoid using a forked version of the extension.  Thanks again!

**Comment by jeffersonking** [comment]
@chrishuynhc Sure, will do that now.

**Comment by jeffersonking** [comment]
@chrishuynhc: 3.3.3 is now published.

**Pull request merged**
