### PR TITLE
Add option for GHAS integration

### PR DESCRIPTION
**Pull request by yongyan-gh**
# Description

The option allows users to enable/disable the GHAS feature.

### CODE REVIEW

**Comment by jeffersonking** [comment]
The `main` branch does not support GHAS. Currently only the `ghas` branch.

**Comment by yongyan-gh** [comment]
> The `main` branch does not support GHAS. Currently only the `ghas` branch.

so I should add this in ghas branch?

**Comment by jeffersonking** [comment]
If you have installing private builds from the `ghas` branch you implicitly want this feature on. Thus we don't need the switch for that branch.

Before `ghas` gets merged to main, we need to decide what mechanism enables/disables the feature. Or perhaps it's always on. As far as I know, the design has not been decided yet (the requirements have not all arrived yet).

**Comment by jeffersonking** [comment]
Closing this due to staleness. We will revisit this when the design of the feature is settled.

**Pull request closed without merging**
